export type AttendanceStatus = "present" | "absent";

export interface AttendanceRecord {
  id: string;
  studentId: string;
  studentName: string;
  date: string;
  status: AttendanceStatus;
  session: string;
}

export const students = [
  {
    id: "1",
    name: "Abebe Kebede",
    email: "abebe@gdgaastu.com",
    coins: 2450,
    attendance: 92,
    track: "Web Development",
    absences: 2,
    joinedDate: "2024-01-15",
    avatar: "AK",
  },
  {
    id: "2",
    name: "Almaz Gebreselassie",
    email: "almaz@gdgaastu.com",
    coins: 1890,
    attendance: 88,
    track: "Mobile Development",
    absences: 4,
    joinedDate: "2024-02-10",
    avatar: "AG",
  },
  {
    id: "3",
    name: "Berhanu Tadesse",
    email: "berhanu@gdgaastu.com",
    coins: 3120,
    attendance: 96,
    track: "Data Science",
    absences: 1,
    joinedDate: "2024-01-20",
    avatar: "BT",
  },
  {
    id: "4",
    name: "Chaltu Yohannes",
    email: "chaltu@gdgaastu.com",
    coins: 1650,
    attendance: 85,
    track: "Web Development",
    absences: 5,
    joinedDate: "2024-03-05",
    avatar: "CY",
  },
  {
    id: "5",
    name: "Dawit Assefa",
    email: "dawit@gdgaastu.com",
    coins: 2780,
    attendance: 94,
    track: "Cloud Computing",
    absences: 2,
    joinedDate: "2024-01-25",
    avatar: "DA",
  },
  {
    id: "6",
    name: "Emebet Mulatu",
    email: "emebet@gdgaastu.com",
    coins: 1200,
    attendance: 78,
    track: "AI/ML",
    absences: 8,
    joinedDate: "2024-04-10",
    avatar: "EM",
  },
];

export const tracks = [
  {
    id: "web-dev",
    slug: "web-dev",
    name: "Web Development",
    description: "Master modern web technologies and build responsive applications",
    mentor: "Dr. Solomon Yohannes",
    icon: "🌐",
    members: 24,
    level: "Intermediate",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "mobile-dev",
    slug: "mobile-dev",
    name: "Mobile Development",
    description: "Create powerful mobile apps with Flutter and React Native",
    mentor: "Eng. Hiwot Assefa",
    icon: "📱",
    members: 18,
    level: "Intermediate",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "data-science",
    slug: "data-science",
    name: "Data Science",
    description: "Analyze data and build predictive models using Python",
    mentor: "Prof. Adnan Mohamed",
    icon: "📊",
    members: 16,
    level: "Advanced",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "cloud-computing",
    slug: "cloud-computing",
    name: "Cloud Computing",
    description: "Deploy and scale applications on cloud platforms",
    mentor: "Eng. Tigist Menelik",
    icon: "☁️",
    members: 14,
    level: "Intermediate",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "ai-ml",
    slug: "ai-ml",
    name: "AI & Machine Learning",
    description: "Build intelligent systems with TensorFlow and PyTorch",
    mentor: "Dr. Abebe Kebede",
    icon: "🤖",
    members: 20,
    level: "Advanced",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "devops",
    slug: "devops",
    name: "DevOps & Infrastructure",
    description: "Master CI/CD, containerization, and infrastructure automation",
    mentor: "Eng. Yohannes Taffa",
    icon: "⚙️",
    members: 12,
    level: "Advanced",
    color: "from-red-500 to-pink-500",
  },
  {
    id: "blockchain",
    slug: "blockchain",
    name: "Blockchain Development",
    description: "Build decentralized applications and smart contracts",
    mentor: "Eng. Kebede Girma",
    icon: "⛓️",
    members: 11,
    level: "Advanced",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "ui-ux",
    slug: "ui-ux",
    name: "UI/UX Design",
    description: "Create beautiful and intuitive user experiences",
    mentor: "Designer Almaz Berhe",
    icon: "🎨",
    members: 15,
    level: "Beginner",
    color: "from-pink-500 to-rose-500",
  },
];

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: "1",
    studentId: "1",
    studentName: "Abebe Kebede",
    date: "2024-12-20",
    status: "present",
    session: "General Session",
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Almaz Gebreselassie",
    date: "2024-12-20",
    status: "absent",
    session: "General Session",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Berhanu Tadesse",
    date: "2024-12-20",
    status: "present",
    session: "General Session",
  },
  {
    id: "4",
    studentId: "1",
    studentName: "Abebe Kebede",
    date: "2024-12-19",
    status: "present",
    session: "Track Session",
  },
  {
    id: "5",
    studentId: "4",
    studentName: "Chaltu Yohannes",
    date: "2024-12-19",
    status: "absent",
    session: "Track Session",
  },
  {
    id: "6",
    studentId: "5",
    studentName: "Dawit Assefa",
    date: "2024-12-19",
    status: "present",
    session: "Track Session",
  },
];

export const dsaProblems = [
  {
    id: "1",
    studentId: "1",
    studentName: "Abebe Kebede",
    problemName: "Two Sum",
    difficulty: "Easy",
    solved: true,
    solvedDate: "2024-12-15",
    language: "Python",
  },
  {
    id: "2",
    studentId: "1",
    studentName: "Abebe Kebede",
    problemName: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    solved: true,
    solvedDate: "2024-12-18",
    language: "Python",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Berhanu Tadesse",
    problemName: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    solved: true,
    solvedDate: "2024-12-10",
    language: "Java",
  },
  {
    id: "4",
    studentId: "5",
    studentName: "Dawit Assefa",
    problemName: "Merge K Sorted Lists",
    difficulty: "Hard",
    solved: true,
    solvedDate: "2024-12-05",
    language: "C++",
  },
];

export const leaderboard = [
  { rank: 1, name: "Berhanu Tadesse", coins: 3120, track: "Data Science" },
  { rank: 2, name: "Dawit Assefa", coins: 2780, track: "Cloud Computing" },
  { rank: 3, name: "Abebe Kebede", coins: 2450, track: "Web Development" },
  { rank: 4, name: "Almaz Gebreselassie", coins: 1890, track: "Mobile Development" },
  { rank: 5, name: "Chaltu Yohannes", coins: 1650, track: "Web Development" },
  { rank: 6, name: "Emebet Mulatu", coins: 1200, track: "AI/ML" },
];

export const recentActivity = [
  {
    id: "1",
    type: "achievement",
    studentName: "Berhanu Tadesse",
    action: "Earned 500 coins",
    timestamp: "2 hours ago",
    icon: "🏆",
  },
  {
    id: "2",
    type: "problem_solved",
    studentName: "Abebe Kebede",
    action: "Solved LeetCode problem",
    timestamp: "4 hours ago",
    icon: "✅",
  },
  {
    id: "3",
    type: "track_completed",
    studentName: "Almaz Gebreselassie",
    action: "Completed Mobile Dev module",
    timestamp: "6 hours ago",
    icon: "🎓",
  },
  {
    id: "4",
    type: "attendance",
    studentName: "Chaltu Yohannes",
    action: "Attended general session",
    timestamp: "1 day ago",
    icon: "📍",
  },
  {
    id: "5",
    type: "achievement",
    studentName: "Dawit Assefa",
    action: "Reached 95% attendance",
    timestamp: "2 days ago",
    icon: "🎯",
  },
];

export const dashboardStats = {
  totalMembers: students.length,
  activeSessionToday: 23,
  averageAttendance: 88.8,
  totalCoinsDistributed: students.reduce((sum, s) => sum + s.coins, 0),
};
